# -*- coding: utf-8 -*-
"""lung_cancer.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p-VIQQdYCgE_eIATeFWU0Yz22WlAvEQZ
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = pd.read_csv('/content/survey lung cancer.csv')
df.head()

df.tail()

df.shape

df.info()

df.describe()

df.isnull().sum()

df.dtypes

sns.countplot(data=df, x="LUNG_CANCER")
plt.title("Lung Cancer Distribution")
plt.show()

sns.histplot(df['AGE'],bins=10, kde=True)
plt.title("Age Distribution")
plt.show()

sns.countplot(data=df, x="GENDER",hue="LUNG_CANCER")
plt.title("Gender vs Lung Cancer")
plt.show()

sns.countplot(data=df,x="SMOKING",hue="LUNG_CANCER")
plt.title("Smoking vs Lung Cancer")
plt.show()

feature = "ALCOHOL CONSUMING"
sns.countplot(data=df, x=feature, hue="LUNG_CANCER")
plt.title(f"ALCOHOL CONSUMINGvs Lung Cancer")
plt.show()

df_encoded = df.copy()

df_encoded["GENDER"] = df_encoded["GENDER"].map({"M": 1, "F": 0})
df_encoded["LUNG_CANCER"] = df_encoded["LUNG_CANCER"].map({"YES": 1, "NO": 0})

plt.figure(figsize=(12, 10))

sns.heatmap(df_encoded.corr(), annot=True, cmap="coolwarm")

plt.title("Correlation Heatmap", fontsize=16)
plt.show()

df["LUNG_CANCER"].value_counts(normalize=True).plot(kind="bar")
plt.title("Percentage of Lung Cancer")
plt.show()

pd.crosstab(df["SMOKING"], df["LUNG_CANCER"], normalize="index").plot(kind="bar")
plt.title("Smoking vs Lung Cancer (%)")
plt.show()

pd.crosstab(df["SMOKING"], df["LUNG_CANCER"]).plot(kind="bar", stacked=True)
plt.title("Smoking vs Lung Cancer (Stacked)")
plt.show()

sns.pairplot(df_encoded, hue="LUNG_CANCER")
plt.show()

corr = df_encoded.corr()["LUNG_CANCER"].sort_values()

corr.plot(kind="barh")
plt.title("Correlation with Lung Cancer")
plt.show()

df["GENDER"] = df["GENDER"].map({"M": 1, "F": 0})

X = df.drop("LUNG_CANCER", axis=1)
y = df["LUNG_CANCER"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

sample = pd.DataFrame([{
    "AGE": 65,
    "GENDER": 1,
    "SMOKING": 2,
    "YELLOW_FINGERS": 2,
    "ANXIETY": 2,
    "PEER_PRESSURE": 1,
    "CHRONIC DISEASE": 1,
    "FATIGUE": 2,
    "ALLERGY": 1,
    "WHEEZING": 2,
    "ALCOHOL CONSUMING": 2,
    "COUGHING": 2,
    "SHORTNESS OF BREATH": 2,
    "SWALLOWING DIFFICULTY": 1,
    "CHEST PAIN": 2
}])

sample = sample[X.columns]

prediction = model.predict(sample)
print(prediction)

from sklearn.metrics import accuracy_score

y_pred = model.predict(X_test)

print("Accuracy:", accuracy_score(y_test, y_pred))

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, y_pred)

sns.heatmap(cm, annot=True, fmt="d")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")
plt.show()